### ISSUE TITLE
npm update-notifier cannot be disabled

### ISSUE THREAD

**Issue by mano184** [chrishelgert/npm-update-notifier#5]
Hi,

I am using Node + Appium. Every time, when i launch appium, npm is checking for latest version and it blocks our test execution for 5 minutes. the update wont happen because we are behind the corporate proxy.

is there any way to permanently or globally disable update-notifier.

or should i remove update-notifier module

**Comment by chrishelgert** [comment]
hey,

i didn´t know anyone is using this tool anymore^^
i think the best way is to remove npm-update-notifier and choose one of the new better choices (for example greenkeeper to keep your dependencies up-to-date)

i will also move this repo to deprecated in favor for this tools.
